/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as AppPropertiesRouteImport } from './routes/app/properties'
import { Route as AppDealsRouteImport } from './routes/app/deals'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppContactsRouteImport } from './routes/app/contacts'
import { Route as AppCompaniesRouteImport } from './routes/app/companies'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app/route',
  path: '/app/route',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPropertiesRoute = AppPropertiesRouteImport.update({
  id: '/app/properties',
  path: '/app/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDealsRoute = AppDealsRouteImport.update({
  id: '/app/deals',
  path: '/app/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/app/dashboard',
  path: '/app/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppContactsRoute = AppContactsRouteImport.update({
  id: '/app/contacts',
  path: '/app/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCompaniesRoute = AppCompaniesRouteImport.update({
  id: '/app/companies',
  path: '/app/companies',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app/companies': typeof AppCompaniesRoute
  '/app/contacts': typeof AppContactsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/deals': typeof AppDealsRoute
  '/app/properties': typeof AppPropertiesRoute
  '/app/route': typeof AppRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/companies': typeof AppCompaniesRoute
  '/app/contacts': typeof AppContactsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/deals': typeof AppDealsRoute
  '/app/properties': typeof AppPropertiesRoute
  '/app/route': typeof AppRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app/companies': typeof AppCompaniesRoute
  '/app/contacts': typeof AppContactsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/deals': typeof AppDealsRoute
  '/app/properties': typeof AppPropertiesRoute
  '/app/route': typeof AppRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app/companies'
    | '/app/contacts'
    | '/app/dashboard'
    | '/app/deals'
    | '/app/properties'
    | '/app/route'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/companies'
    | '/app/contacts'
    | '/app/dashboard'
    | '/app/deals'
    | '/app/properties'
    | '/app/route'
  id:
    | '__root__'
    | '/'
    | '/app/companies'
    | '/app/contacts'
    | '/app/dashboard'
    | '/app/deals'
    | '/app/properties'
    | '/app/route'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppCompaniesRoute: typeof AppCompaniesRoute
  AppContactsRoute: typeof AppContactsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDealsRoute: typeof AppDealsRoute
  AppPropertiesRoute: typeof AppPropertiesRoute
  AppRouteRoute: typeof AppRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/route': {
      id: '/app/route'
      path: '/app/route'
      fullPath: '/app/route'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/properties': {
      id: '/app/properties'
      path: '/app/properties'
      fullPath: '/app/properties'
      preLoaderRoute: typeof AppPropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/deals': {
      id: '/app/deals'
      path: '/app/deals'
      fullPath: '/app/deals'
      preLoaderRoute: typeof AppDealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/app/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/contacts': {
      id: '/app/contacts'
      path: '/app/contacts'
      fullPath: '/app/contacts'
      preLoaderRoute: typeof AppContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/companies': {
      id: '/app/companies'
      path: '/app/companies'
      fullPath: '/app/companies'
      preLoaderRoute: typeof AppCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppCompaniesRoute: AppCompaniesRoute,
  AppContactsRoute: AppContactsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDealsRoute: AppDealsRoute,
  AppPropertiesRoute: AppPropertiesRoute,
  AppRouteRoute: AppRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
